{
  "name": "YouthEdEventsDashboard",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true,
      "fastCombine": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "DIMDate",
        "description": "DAX Date Dimension",
        "lineageTag": "6488d42f-510a-422c-a769-a9a83acd59fa",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Primary key",
            "isKey": true,
            "sourceColumn": "[Date]",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "da554ecd-0892-4a07-b52d-6dc30198ddd6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "School Year",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "School year-ending (like 2020/2021)",
            "sourceColumn": "[School Year]",
            "sortByColumn": "School Year Sort",
            "lineageTag": "c07ff3ae-384f-4dae-8496-2d937a33ccdf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Month name",
            "sourceColumn": "[Month]",
            "sortByColumn": "Month Sort",
            "lineageTag": "db0186c0-c6d7-4c14-bb42-9f9e21b81f83",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Month Sort",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Sort order for Month name",
            "isHidden": true,
            "sourceColumn": "[Month Sort]",
            "formatString": "0",
            "lineageTag": "d094afa4-de18-4859-bbc6-fcddc3a88716",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "School Year Sort",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[School Year Sort]",
            "formatString": "0",
            "lineageTag": "e3c1b822-4b4c-4194-bbb6-68f21d9a3522",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "School Year Completed",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": [
              "",
              "IF(",
              "    YEAR(DIMDate[Date]) >= YEAR(TODAY())",
              "    && MONTH(DIMDate[Date]) >= 9,",
              "    FALSE,",
              "    TRUE()",
              ")"
            ],
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isAvailableInMdx": false,
            "lineageTag": "c0a37018-6ac9-481f-a648-6b3e54a003ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIMDate-92908765-b374-44e9-a902-ddc4f88cdf48",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "VAR MinYear =",
                "    YEAR (",
                "        MIN ( FACT_PeopleEvents[Event Date] )",
                "    )",
                "VAR MaxYear =",
                "    YEAR (",
                "        MAX ( FACT_PeopleEvents[Event Date] )",
                "    )",
                "VAR SchoolBeginMonth = 9",
                "RETURN",
                "    ADDCOLUMNS (",
                "        FILTER (",
                "            CALENDARAUTO (),",
                "            AND (",
                "                YEAR ( [Date] ) >= MinYear,",
                "                YEAR ( [Date] ) <= MaxYear",
                "            )",
                "        ),",
                "        \"School Year\",",
                "            IF (",
                "                MONTH ( [Date] ) < SchoolBeginMonth,",
                "                YEAR ( [Date] ) - 1 & \"/\"",
                "                    & YEAR ( [Date] ),",
                "                YEAR ( [Date] ) & \"/\"",
                "                    & YEAR ( [Date] ) + 1",
                "            ),",
                "        \"School Year Sort\",",
                "            IF (",
                "                MONTH ( [Date] ) < SchoolBeginMonth,",
                "                YEAR( [Date] ) - 1,",
                "                YEAR( [Date] )",
                "            ),",
                "        \"Month\",",
                "            FORMAT (",
                "                [Date],",
                "                \"mmm\"",
                "            ),",
                "        \"Month Sort\",",
                "            SWITCH (",
                "                TRUE,",
                "                MONTH ( [Date] ) = 9, 1,",
                "                MONTH ( [Date] ) = 10, 2,",
                "                MONTH ( [Date] ) = 11, 3,",
                "                MONTH ( [Date] ) = 12, 4,",
                "                MONTH ( [Date] ) = 1, 5,",
                "                MONTH ( [Date] ) = 2, 6,",
                "                MONTH ( [Date] ) = 3, 7,",
                "                MONTH ( [Date] ) = 4, 8,",
                "                MONTH ( [Date] ) = 5, 9,",
                "                MONTH ( [Date] ) = 6, 10,",
                "                MONTH ( [Date] ) = 7, 11,",
                "                12",
                "            )",
                "    )"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a768ae4f4e124a09ab742ec8bd56f261"
          }
        ]
      },
      {
        "name": "@SchoolMeasures",
        "description": "Contains DAX measures for SchoolData facts",
        "lineageTag": "82bb370c-07dc-4c32-be60-caa3187aacbc",
        "partitions": [
          {
            "name": "@SchoolMeasures",
            "mode": "import",
            "queryGroup": "DAX Containers",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Students_%POC",
            "description": "Proportion of students who are people of color (non-white)",
            "expression": [
              "VAR POCStudents =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Students] * ( 1 - FACT_SchoolData[Student % White] )",
              "    )",
              "VAR TotalStudents = [Students_TotalNum]",
              "RETURN",
              "    DIVIDE ( POCStudents, TotalStudents, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "e637456e-de47-4b46-9b03-045ecbdfffd3"
          },
          {
            "name": "Students_TotalNum",
            "description": "Number of students",
            "expression": [
              "VAR TotalStudents =",
              "    SUM ( FACT_SchoolData[Total Students] )",
              "RETURN",
              "    IF ( ISBLANK ( TotalStudents ), 0, TotalStudents )"
            ],
            "formatString": "#,0",
            "lineageTag": "f34834ef-dc24-481b-bace-6c2f8a5efc01"
          },
          {
            "name": "Teachers_TotalNum",
            "description": "Number of teachers",
            "expression": [
              "VAR TotalTeachers =",
              "    SUM ( FACT_SchoolData[Total Teachers] )",
              "RETURN",
              "    IF ( ISBLANK ( TotalTeachers ), 0, TotalTeachers )"
            ],
            "formatString": "#,0",
            "lineageTag": "a4a1b9c2-63a1-48ab-a97f-36cbec03c15f"
          },
          {
            "name": "Teachers_%POC",
            "description": "Proportion of teachers who are people of color (non-white)",
            "expression": [
              "VAR POCTeachers =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Teachers] * ( 1 - FACT_SchoolData[Teacher % White] )",
              "    )",
              "VAR TotalTeachers = [Teachers_TotalNum]",
              "RETURN",
              "    DIVIDE ( POCTeachers, TotalTeachers, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "38f91924-94f1-4457-8c8d-009d5df8a913"
          },
          {
            "name": "Teachers_%Experience",
            "description": "Proportion of teachers who \"are experienced\" as measured by an unknown method (schooling?  length of career?)",
            "expression": [
              "VAR ExperiencedTeachers =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Teachers] * FACT_SchoolData[Teacher Experience]",
              "    )",
              "VAR TotalTeachers = [Teachers_TotalNum]",
              "RETURN",
              "    DIVIDE ( ExperiencedTeachers, TotalTeachers, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "63794e74-e9ac-40b0-b4ac-e7709eba3a1b"
          },
          {
            "name": "Students_%Immune",
            "description": "Proportion of students who have had all required immunizations",
            "expression": [
              "VAR ImmuneStudents =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Students] * 'FACT_SchoolData'[Required Immunizations]",
              "    )",
              "VAR TotalStudents = [Students_TotalNum]",
              "RETURN",
              "    DIVIDE ( ImmuneStudents, TotalStudents, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "7dae50fe-6ab1-44b9-a00d-cb13b874a3c6"
          },
          {
            "name": "Students_%FRPL",
            "description": "Proportion of students who receive free or reduced-priced lunch",
            "expression": [
              "VAR FRPLStudents =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Students] * 'FACT_SchoolData'[Free/Reduced Price Lunch Eligible]",
              "    )",
              "VAR TotalStudents = [Students_TotalNum]",
              "RETURN",
              "    DIVIDE ( FRPLStudents, TotalStudents, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "3ec150f8-764a-4f4c-a0fe-adbf9eb51d84"
          },
          {
            "name": "Teacher_%Retention",
            "description": "Proportion of teachers who \"are retained\" (not sure if this is a time duration or what)",
            "expression": [
              "VAR RetainedTeachers =",
              "    SUMX (",
              "        FACT_SchoolData,",
              "        FACT_SchoolData[Total Teachers] * 'FACT_SchoolData'[Average Teacher Retention Rate]",
              "    )",
              "VAR TotalTeachers = [Teachers_TotalNum]",
              "RETURN",
              "    DIVIDE ( RetainedTeachers, TotalTeachers, 0 )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "99be5235-5efc-479a-8e46-80700f66815d"
          },
          {
            "name": "Title 1",
            "description": "Proportion of schools that are Title 1",
            "expression": [
              "AVERAGEX (",
              "    FACT_SchoolData,",
              "    IF ( 'FACT_SchoolData'[Title 1 School] = \"yes\", 1, 0 )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "7ea225e6-522d-4497-ba72-bcfceb450daa",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "SamePrinciple",
            "description": "Proportion of schools with the same principal in the last two years",
            "expression": [
              "AVERAGEX (",
              "    FACT_SchoolData,",
              "    IF ( 'FACT_SchoolData'[Same Principal in the Last 3 Years] = \"yes\", 1, 0 )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "fe9d7e87-dcd5-4e07-b13d-169e9260f34f",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FACT_PeopleEvents",
        "description": "Event-level fact table",
        "isHidden": true,
        "lineageTag": "047ad52a-fc09-46a1-8261-9299640e80ba",
        "columns": [
          {
            "name": "Event Date",
            "dataType": "dateTime",
            "description": "Date of event",
            "isHidden": true,
            "sourceColumn": "Event Date",
            "formatString": "mm/dd/yyyy",
            "isAvailableInMdx": false,
            "lineageTag": "f721ffdc-70bd-4acd-b8ee-e996affd79e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Grade ID",
            "dataType": "int64",
            "description": "foreign key for grade",
            "isHidden": true,
            "sourceColumn": "Grade ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "b09adeca-eb3e-44a4-bef8-57759968d5f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "School ID",
            "dataType": "int64",
            "description": "Foreign key for school name",
            "isHidden": true,
            "sourceColumn": "School ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "675346e7-610e-457c-83e8-318112f5e1b5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Educator ID",
            "dataType": "int64",
            "description": "Foreign key for Educator",
            "isHidden": true,
            "sourceColumn": "Educator ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "864f3b96-0e66-4c20-8b03-8291878fc47b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "People",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "People",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "fb3b319f-4abd-442d-abc9-960d10bb1cc0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Program ID",
            "dataType": "int64",
            "description": "Foreign key for program",
            "isHidden": true,
            "sourceColumn": "Program ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "d21189c6-1122-4841-a080-2392b4e61055",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Event Type ID",
            "dataType": "int64",
            "description": "Foreign key for event type",
            "isHidden": true,
            "sourceColumn": "Event Type ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "98782757-4622-4c3b-8201-e75f6e7b05ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Duration",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Duration",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "eaa9ab41-cfc6-413d-af40-36b38adbc04a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FACT_PeopleEvents",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Events,",
                "    ",
                "    // Replace Grade Descr with Grade ID",
                "    GradeDim_Task1 = Table.NestedJoin(Source, {\"Grade\"}, DIM_Grades, {\"Grade\"}, \"DIM_Grades\", JoinKind.LeftOuter),",
                "    GradeDim_Task2 = Table.ExpandTableColumn(GradeDim_Task1, \"DIM_Grades\", {\"Grade ID\"}, {\"Grade ID\"}),",
                "    GradeDim_Task3 = Table.RemoveColumns(GradeDim_Task2,{\"Grade\"}),",
                "    ",
                "    // Replace School Descr with School ID",
                "    SchoolDim_Task1 = Table.NestedJoin(GradeDim_Task3, {\"School Event Location\"}, DIM_Schools, {\"School Name\"}, \"DIM_Schools\", JoinKind.LeftOuter),",
                "    SchoolDim_Task2 = Table.ExpandTableColumn(SchoolDim_Task1, \"DIM_Schools\", {\"School ID\"}, {\"School ID\"}),",
                "    SchoolDim_Task3 = Table.RemoveColumns(SchoolDim_Task2,{\"School Event Location\"}),",
                "    ",
                "    // Replace Program Name Descr with Program ID",
                "    EventDim_Task1 = Table.NestedJoin(SchoolDim_Task3, {\"Program Name\"}, DIM_Programs, {\"Program Name\"}, \"DIM_Programs\", JoinKind.LeftOuter),",
                "    EventDim_Task2 = Table.ExpandTableColumn(EventDim_Task1, \"DIM_Programs\", {\"Program ID\"}, {\"Program ID\"}),",
                "    EventDim_Task3 = Table.RemoveColumns(EventDim_Task2,{\"Program Name\"}),",
                "    ",
                "    // Replace Educator Name with Educator ID",
                "    EducatorDim_Task1 = Table.NestedJoin(EventDim_Task3, {\"Educator\"}, DIM_Educators, {\"Educator\"}, \"DIM_Educators\", JoinKind.LeftOuter),",
                "    EducatorDim_Task2 = Table.ExpandTableColumn(EducatorDim_Task1, \"DIM_Educators\", {\"Educator ID\"}, {\"Educator ID\"}),",
                "    EducatorDim_Task3 = Table.RemoveColumns(EducatorDim_Task2,{\"Educator\"}),",
                "      ",
                "    // Replace Event Type Descr with Event Type ID",
                "    EventTypeDim_Task1 = Table.NestedJoin(EducatorDim_Task3, {\"Event Type\"}, DIM_EventType, {\"Event Type\"}, \"DIM_EventType\", JoinKind.LeftOuter),",
                "    EventTypeDim_Task2 = Table.ExpandTableColumn(EventTypeDim_Task1, \"DIM_EventType\", {\"Event Type ID\"}, {\"Event Type ID\"}),",
                "    EventTypeDim_Task3 = Table.RemoveColumns(EventTypeDim_Task2,{\"Event Type\"})",
                "in",
                "    EventTypeDim_Task3"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "FACT_SchoolData",
        "description": "School-level fact table",
        "isHidden": true,
        "lineageTag": "faae06a0-6169-49cd-833d-0ac4f06fd167",
        "columns": [
          {
            "name": "Required Immunizations",
            "dataType": "double",
            "description": "Immunization rate of required immunizations amongst student body",
            "isHidden": true,
            "sourceColumn": "Required Immunizations",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "9356a2cc-732d-4c1c-a9aa-1d4cbb9a5a7b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Teacher Experience",
            "dataType": "double",
            "description": "Percentage of teachers with a certain level or years of experience (not certain of measure)",
            "isHidden": true,
            "sourceColumn": "Teacher Experience",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "fad2df0f-b0f8-4a98-a730-5a82e26ce322",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Same Principal in the Last 3 Years",
            "dataType": "string",
            "description": "Has school has same principal in last 3 years (yes or no)",
            "isHidden": true,
            "sourceColumn": "Same Principal in the Last 3 Years",
            "isAvailableInMdx": false,
            "lineageTag": "5b7a28a6-8c11-4c3a-a336-65fef19ccfc6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Average Teacher Retention Rate",
            "dataType": "double",
            "description": "Teacher retention rate",
            "isHidden": true,
            "sourceColumn": "Average Teacher Retention Rate",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "4179392f-6e4a-4a0b-a6a8-458af8bcfd34",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "School ID",
            "dataType": "int64",
            "description": "Foreign key for school name",
            "isHidden": true,
            "sourceColumn": "School ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "975b5460-fe4d-4f49-a424-d9f74f77c2ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Total Students",
            "dataType": "int64",
            "description": "Total number of students in school",
            "isHidden": true,
            "sourceColumn": "Total Students",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "0d6155fc-7a26-43b5-b6c8-f6da35f20cb2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Student % White",
            "dataType": "double",
            "description": "Percentage of students that are white",
            "isHidden": true,
            "sourceColumn": "Student % White",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "e82f0253-8097-4293-95f4-b1ccbc897b89",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Total Teachers",
            "dataType": "int64",
            "description": "Total number of teachers in school",
            "isHidden": true,
            "sourceColumn": "Total Teachers",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "0368c616-03cd-44e4-8de3-f1aa5c8948e7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Teacher % White",
            "dataType": "double",
            "description": "Percentage of teachers that are white",
            "isHidden": true,
            "sourceColumn": "Teacher % White",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "bfb6e38d-23c9-4047-9949-5402fefead52",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Free/Reduced Price Lunch Eligible",
            "dataType": "double",
            "description": "Percentage of students with free or reduced price lunch",
            "isHidden": true,
            "sourceColumn": "Free/Reduced Price Lunch Eligible",
            "formatString": "0%;-0%;0%",
            "isAvailableInMdx": false,
            "lineageTag": "be58d4ed-3f26-4d6f-9eea-e48361cd6e9e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Title 1 School",
            "dataType": "string",
            "description": "Title 1 status, either full or partial (yes or no)",
            "isHidden": true,
            "sourceColumn": "Title 1 School",
            "isAvailableInMdx": false,
            "lineageTag": "326d33f4-341c-4946-a80f-1346cb8d9e76",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "FACT_SchoolData",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Schools,",
                "    ",
                "    // Replace School Name with School ID",
                "    SchoolDim_Task1 = Table.NestedJoin(Source, {\"School Name\"}, DIM_Schools, {\"School Name\"}, \"DIM_Schools\", JoinKind.LeftOuter),",
                "    SchoolDim_Task2 = Table.ExpandTableColumn(SchoolDim_Task1, \"DIM_Schools\", {\"School ID\"}, {\"School ID\"}),",
                "    SchoolDim_Task3 = Table.RemoveColumns(SchoolDim_Task2,{\"District Name\", \"School Name\", \"Street\", \"City\", \"State\", \"Zip\", \"County\", \"Lat\", \"Long\", \"Grades\"})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    SchoolDim_Task3,{\"Student % Hispanic\",\"Student % Asian\",\"Student % Black\",\"Counselors/Psychologists\",\"Student % Multi\",\"Teacher % Hispanic\",\"Student % Islander\",\"Teacher % Asian\",\"Teacher % Multi\",\"Student % Native\",\"Teacher % Black\",\"Educational Assistants\",\"Teacher % Native\",\"Teacher % Islander\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"IsHidden\"]"
          }
        ]
      },
      {
        "name": "DIM_Grades",
        "description": "Grades",
        "lineageTag": "370c79da-8af5-41b4-a912-ed2fc608fa3d",
        "columns": [
          {
            "name": "Grade ID",
            "dataType": "int64",
            "description": "Primary key",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "Grade ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "6beba31e-c5b3-4dac-9e8b-5d5519a1065b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Grade",
            "dataType": "string",
            "description": "School grade level (PK - 12), plus \"Mixed\" and \"Non-school\" values",
            "sourceColumn": "Grade",
            "sortByColumn": "GradeSort",
            "lineageTag": "99f302b4-4a5e-4ab7-b0a9-cc155dd37181",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ]
          },
          {
            "name": "GradeSort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GradeSort",
            "formatString": "0",
            "lineageTag": "5cbe0e2c-8cac-4e05-b024-5a620d6bba2d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Grade Type",
            "dataType": "string",
            "description": "Elementary or seondary",
            "sourceColumn": "Grade Type",
            "lineageTag": "8bd7217c-ea6c-411a-b17f-b64fd95d3419",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_Grades",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Events,",
                "",
                "    // Remove extraneous columns not needed in Power BI dashboard",
                "    SelGradeCol = Table.SelectColumns(Source, {\"Grade\"}),",
                "    ",
                "    // Set column data types",
                "    SetDataTypes = Table.TransformColumnTypes(SelGradeCol,{{\"Grade\", type text}}),",
                "    ",
                "    // Remove Duplicate Values",
                "    RemoveDuplicates = Table.Distinct(SetDataTypes),",
                "",
                "    // Create Primary key",
                "    PrimaryKey_Task1 = Table.AddIndexColumn(RemoveDuplicates, \"Index\", 1, 1, Int64.Type),",
                "    PrimaryKey_Task2 = Table.ReorderColumns(PrimaryKey_Task1,{\"Index\", \"Grade\"}),",
                "    PrimaryKey_Task3 = Table.RenameColumns(PrimaryKey_Task2,{{\"Index\", \"Grade ID\"}}),",
                "    ",
                "    // Add some necessary columns",
                "    GradeSort = Table.AddColumn(PrimaryKey_Task3, \"GradeSort\", each if [Grade] = \"K\" then 1 else if [Grade] = \"1st\" then 2 else if [Grade] = \"2nd\" then 3 else if [Grade] = \"3rd\" then 4 else if [Grade] = \"4th\" then 5 else if [Grade] = \"5th\" then 6 else if [Grade] = \"6th\" then 7 else if [Grade] = \"7th\" then 8 else if [Grade] = \"8th\" then 9 else if [Grade] = \"9th\" then 10 else if [Grade] = \"10th\" then 11 else if [Grade] = \"11th\" then 12 else if [Grade] = \"12th\" then 13 else if [Grade] = \"Mixed Grades - Ele\" then 14 else if [Grade] = \"Mixed Grades - MS\" then 15 else 16),",
                "    GradeSortType = Table.TransformColumnTypes(GradeSort,{{\"GradeSort\", Int64.Type}}),",
                "    GradeType = Table.AddColumn(GradeSortType, \"Grade Type\", each if [Grade] = \"K\" then \"Elementary\" else if [Grade] = \"1st\" then \"Elementary\" else if [Grade] = \"2nd\" then \"Elementary\" else if [Grade] = \"3rd\" then \"Elementary\" else if [Grade] = \"4th\" then \"Elementary\" else if [Grade] = \"5th\" then \"Elementary\" else if [Grade] = \"Mixed Grades - Ele\" then \"Elementary\" else \"Secondary\"),",
                "    GradeTypeType = Table.TransformColumnTypes(GradeType,{{\"Grade Type\", type text}})",
                "in",
                "    GradeTypeType"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_Schools",
        "description": "Schools dimension holding all schools, both public and private that are serviced by ed team",
        "lineageTag": "82a4c0a1-c60a-4901-b7dd-e7e794c9362d",
        "columns": [
          {
            "name": "School ID",
            "dataType": "int64",
            "description": "Primary key",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "School ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "dde20568-9aee-4a37-ac4f-9103b3431841",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "School Name",
            "dataType": "string",
            "description": "School name",
            "isNullable": false,
            "sourceColumn": "School Name",
            "lineageTag": "8089934c-d4eb-42f7-896f-cd32d87a19fc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "County",
            "dataType": "string",
            "description": "County",
            "sourceColumn": "County",
            "lineageTag": "fcba167c-ff19-4ab7-a1d2-a72a646366b9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "District Name",
            "dataType": "string",
            "description": "School district",
            "sourceColumn": "District Name",
            "lineageTag": "479abd55-35d6-4ccd-bf24-364c99ef3744",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"SortByColumn\"]"
              }
            ]
          },
          {
            "name": "Lat",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Lat",
            "isAvailableInMdx": false,
            "lineageTag": "827d342b-c7aa-4514-806b-9c5e3730e49e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Long",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Long",
            "isAvailableInMdx": false,
            "lineageTag": "ec47740a-263b-4fbd-aa21-6af915bbff8e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_Schools",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Schools,",
                "",
                "    // Remove extraneous columns not needed in Power BI dashboard",
                "    RemoveExtraneousColumns = Table.SelectColumns(Source,{\"District Name\", \"School Name\", \"City\", \"County\", \"Lat\", \"Long\", \"Grades\"}),",
                "    ",
                "    // Set the column data types",
                "    SetDataTypes = Table.TransformColumnTypes(RemoveExtraneousColumns,{{\"District Name\", type text}, {\"School Name\", type text}, {\"City\", type text}, {\"County\", type text}, {\"Lat\", type number}, {\"Long\", type number},{\"Grades\", type text}}),",
                "    ",
                "    // Remove any duplicate entries",
                "    RemoveDuplicates = Table.Distinct(SetDataTypes),",
                "    ",
                "    // Add and arrange primary key field",
                "    PrimaryKey_Task1 = Table.AddIndexColumn(RemoveDuplicates, \"Index\", 1, 1, Int64.Type),",
                "    PrimaryKey_Task2 = Table.ReorderColumns(PrimaryKey_Task1,{\"Index\", \"District Name\", \"School Name\", \"City\", \"County\", \"Lat\", \"Long\", \"Grades\"}),",
                "    PrimaryKey_Task3 = Table.RenameColumns(PrimaryKey_Task2,{{\"Index\", \"School ID\"}})",
                ",",
                "#\"Columns removed by Measure Killer\"= Table.RemoveColumns(    PrimaryKey_Task3,{\"City\",\"Grades\"})",
                "in",
                "#\"Columns removed by Measure Killer\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_Programs",
        "description": "Event/Presentation Names",
        "lineageTag": "d6a8a17d-8960-4b71-9e59-894c82584427",
        "columns": [
          {
            "name": "Program ID",
            "dataType": "int64",
            "description": "Primary key",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "Program ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "0937306e-86c1-4b1f-9ed0-226250d5c847",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Program Name",
            "dataType": "string",
            "description": "Event/Program/Presentation name",
            "sourceColumn": "Program Name",
            "lineageTag": "edfc417b-5396-4be1-a11f-826beb4038f3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_Programs",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Events,",
                "",
                "    // Remove extraneous columns not needed in Power BI dashboard",
                "    SelPNCol = Table.SelectColumns(Source, {\"Program Name\"}),",
                "    ",
                "    // Set column data types",
                "    SetDataTypes = Table.TransformColumnTypes(SelPNCol,{{\"Program Name\", type text}}),",
                "    ",
                "    // Remove Duplicate Values",
                "    RemoveDuplicates = Table.Distinct(SetDataTypes),",
                "",
                "    // Create Primary key",
                "    PrimaryKey_Task1 = Table.AddIndexColumn(RemoveDuplicates, \"Index\", 1, 1, Int64.Type),",
                "    PrimaryKey_Task2 = Table.ReorderColumns(PrimaryKey_Task1,{\"Index\", \"Program Name\"}),",
                "    PrimaryKey_Task3 = Table.RenameColumns(PrimaryKey_Task2,{{\"Index\", \"Program ID\"}})",
                "",
                "in",
                "    PrimaryKey_Task3"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "DIM_Educators",
        "description": "Educators/Presenters",
        "lineageTag": "df45f04f-364e-4ec4-9c94-c15a1dea046e",
        "columns": [
          {
            "name": "Educator ID",
            "dataType": "int64",
            "description": "Primary key",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "Educator ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "6596a868-23e2-4ca5-9bec-5f0243b490b7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Educator",
            "dataType": "string",
            "description": "Educator name",
            "sourceColumn": "Educator",
            "lineageTag": "f881bb4b-bfca-404e-9bdc-a0cf70a32062",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_Educators",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Events,",
                "",
                "    // Remove extraneous columns not needed in Power BI dashboard",
                "    SelEducatorCol = Table.SelectColumns(Source, {\"Educator\"}),",
                "    ",
                "    // Set column data types",
                "    SetDataTypes = Table.TransformColumnTypes(SelEducatorCol,{{\"Educator\", type text}}),",
                "    ",
                "    // Remove Duplicate Values",
                "    RemoveDuplicates = Table.Distinct(SetDataTypes),",
                "",
                "    // Create Primary key",
                "    PrimaryKey_Task1 = Table.AddIndexColumn(RemoveDuplicates, \"Index\", 1, 1, Int64.Type),",
                "    PrimaryKey_Task2 = Table.ReorderColumns(PrimaryKey_Task1,{\"Index\", \"Educator\"}),",
                "    PrimaryKey_Task3 = Table.RenameColumns(PrimaryKey_Task2,{{\"Index\", \"Educator ID\"}})",
                "",
                "in",
                "    PrimaryKey_Task3"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "@PeopleEventMeasures",
        "description": "Contains DAX measures for PeopleEvent facts",
        "lineageTag": "bd7bd527-625d-4bc3-9039-8b93bbca82e5",
        "partitions": [
          {
            "name": "@PeopleEventMeasures",
            "mode": "import",
            "queryGroup": "DAX Containers",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Events",
            "description": "Delivered events",
            "expression": "COUNTROWS (FACT_PeopleEvents)",
            "formatString": "#,0",
            "lineageTag": "9544a620-a2f3-4304-a240-b1323aad4dcc"
          },
          {
            "name": "Students Reached",
            "description": "Total contacts made whose status equals \"Delivered\"",
            "expression": "SUM (FACT_PeopleEvents[People])",
            "formatString": "#,0",
            "lineageTag": "3496a22e-fa15-4765-9bca-122d918a5273"
          },
          {
            "name": "Last Visit",
            "description": "Last event date, calculated per school for seeing when last time school was visited",
            "expression": [
              "",
              "VAR LastEventDate =",
              "    MAX (FACT_PeopleEvents[Event Date])",
              "RETURN",
              "    IF ( ISBLANK ( LastEventDate ), \"No Visit\", LastEventDate )"
            ],
            "formatString": "#,0",
            "lineageTag": "ad8d23d5-dfb7-4a57-8b88-1ff17972ea8e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"FormatString\"]"
              }
            ]
          },
          {
            "name": "Duration",
            "description": "Duration of all delivered events, in minutes",
            "expression": "SUM (FACT_PeopleEvents[Duration])",
            "formatString": "#,0",
            "lineageTag": "589bf63a-1450-4220-afe4-39ade7c20ffd"
          },
          {
            "name": "% Total Students",
            "description": "Percentage of total students reached by education activities",
            "expression": "DIVIDE ( [Students Reached], [Students_TotalNum] )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "f7a727a9-9291-47cb-85c3-a8d7356b7f1c"
          },
          {
            "name": "ReachedTarget",
            "description": "Student population target for education activity reach (currently 5%)",
            "expression": ".05",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "eb085a81-69bb-4263-ab7a-40403c342862"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "@FormatLabelMeasures",
        "description": "Contains DAX that controls dynamic formatting, labeling and titling of visualizations",
        "isHidden": true,
        "lineageTag": "7bdc79d0-f5da-4456-b23c-460188dad804",
        "partitions": [
          {
            "name": "@FormatLabelMeasures",
            "mode": "import",
            "queryGroup": "DAX Containers",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Result_Format",
            "description": "Measure used to highlight schools visited in scatter plot of School Analysis page",
            "expression": [
              "IF (",
              "    [Events] > 0,",
              "    \"#16A8B5\",",
              "    \"#003B5C\"",
              ")"
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "5ce8cc87-67ca-4f01-9a83-9b661fba49ca",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "ScatterTitle",
            "description": "Dynamic title of scatter plot based on x and y axis selections",
            "expression": [
              "VAR SelXAxis =",
              "    SELECTEDVALUE ( '@DynamicMeasureTable_Axis1'[Axis 1 Measure] )",
              "VAR SelYAxis =",
              "    SELECTEDVALUE ( '@DynamicMeasureTable_Axis2'[Axis 2 Measure] )",
              "RETURN",
              "    \"Schools by \" & SelXAxis & \" (x) and \" & SelYAxis & \" (y)\""
            ],
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "c83dd8dc-339f-4101-a0d1-eebcba7ce30e",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "TheAlberto",
            "expression": "INT ( NOT ISEMPTY (FACT_PeopleEvents) )",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "1a32bd32-5613-4c53-91df-c96e4063ae04",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "KPITrend_FC",
            "expression": [
              "",
              "VAR MaxFilters = 3",
              "RETURN",
              "IF ( ",
              "    ISFILTERED ( DIM_Educators[Educator] ), ",
              "    VAR ___f = FILTERS ( DIM_Educators[Educator] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Educators[Educator] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Educators[Educator], \", \" )",
              "    VAR ___x = \"Educator = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_EventType[Event Type] ), ",
              "    VAR ___f = FILTERS ( DIM_EventType[Event Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_EventType[Event Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_EventType[Event Type], \", \" )",
              "    VAR ___x = \"Event Type = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Grades[Grade] ), ",
              "    VAR ___f = FILTERS ( DIM_Grades[Grade] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Grades[Grade] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Grades[Grade], \", \" )",
              "    VAR ___x = \"Grade = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Grades[Grade Type] ), ",
              "    VAR ___f = FILTERS ( DIM_Grades[Grade Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Grades[Grade Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Grades[Grade Type], \", \" )",
              "    VAR ___x = \"Grade Type = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Programs[Program Name] ), ",
              "    VAR ___f = FILTERS ( DIM_Programs[Program Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Programs[Program Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Programs[Program Name], \", \" )",
              "    VAR ___x = \"Program = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Schools[District Name] ), ",
              "    VAR ___f = FILTERS ( DIM_Schools[District Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Schools[District Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Schools[District Name], \", \" )",
              "    VAR ___x = \"District = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Schools[School Name] ), ",
              "    VAR ___f = FILTERS ( DIM_Schools[School Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Schools[School Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Schools[School Name], \", \" )",
              "    VAR ___x = \"School = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "1d4ed721-1be3-49a3-9927-59a6a896af44",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "DataExplorer_FC",
            "expression": [
              "",
              "VAR MaxFilters = 3",
              "RETURN",
              "IF ( ",
              "    ISFILTERED ( DIM_Grades[Grade Type] ), ",
              "    VAR ___f = FILTERS ( DIM_Grades[Grade Type] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Grades[Grade Type] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Grades[Grade Type], \", \" )",
              "    VAR ___x = \"Grade Type = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Schools[District Name] ), ",
              "    VAR ___f = FILTERS ( DIM_Schools[District Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Schools[District Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Schools[District Name], \", \" )",
              "    VAR ___x = \"District = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIM_Schools[School Name] ), ",
              "    VAR ___f = FILTERS ( DIM_Schools[School Name] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIM_Schools[School Name] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIM_Schools[School Name], \", \" )",
              "    VAR ___x = \"School = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              " & IF ( ",
              "    ISFILTERED ( DIMDate[School Year] ), ",
              "    VAR ___f = FILTERS ( DIMDate[School Year] ) ",
              "    VAR ___r = COUNTROWS ( ___f ) ",
              "    VAR ___t = TOPN ( MaxFilters, ___f, DIMDate[School Year] )",
              "    VAR ___d = CONCATENATEX ( ___t, DIMDate[School Year], \", \" )",
              "    VAR ___x = \"Year = \" & ___d & IF(___r > MaxFilters, \", ... [\" & ___r & \" items selected]\") & \" \" ",
              "    RETURN ___x & UNICHAR(13) & UNICHAR(10)",
              ")",
              ""
            ],
            "isHidden": true,
            "lineageTag": "49ff5a5f-e5ce-4f6e-8de4-a7105e9ca5f4",
            "annotations": [
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"IsHidden\"]"
          }
        ]
      },
      {
        "name": "@DynamicMeasureTable_Axis1",
        "description": "Disconnected table for allowing users to select their measure of choice for the x-axis of the scatter plot on the School Analysis page",
        "isHidden": true,
        "lineageTag": "0d136303-6597-4ca3-8a55-5b126711bab3",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Axis 1 Measure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Measure name column of disconnected table",
            "isHidden": true,
            "sourceColumn": "[Axis 1 Measure]",
            "sortByColumn": "Sort Order",
            "lineageTag": "a9506bc8-f1cb-4b50-a261-bebb0dbccceb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Sort Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Sort order of measure name column",
            "isHidden": true,
            "sourceColumn": "[Sort Order]",
            "formatString": "0",
            "lineageTag": "c81181a0-e60e-46b3-95ca-988b96dbb59e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@DynamicMeasureTable_Axis1-727b531c-c9f8-4f9d-b766-263a2495950d",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "DATATABLE (",
                "    \"Axis 1 Measure\", STRING,",
                "    \"Sort Order\", INTEGER,",
                "    {",
                "        { \"% Students of Color\", 1 },",
                "        { \"% Teachers of Color\", 2 },",
                "        { \"Teacher Experience %\", 3 },",
                "        { \"% Req Immunizations\", 4 },",
                "        { \"% Students Free/Reduced Lunch\", 5 },",
                "        { \"Teacher Retention %\", 6 }",
                "    }",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "X-Axis",
            "description": "DAX measure for users' selected x-axis measure",
            "expression": [
              "VAR Selection =",
              "    SELECTEDVALUE ( '@DynamicMeasureTable_Axis1'[Axis 1 Measure] )",
              "RETURN",
              "    SWITCH (",
              "        Selection,",
              "        \"% Students of Color\", [Students_%POC],",
              "        \"% Teachers of Color\", [Teachers_%POC],",
              "        \"Teacher Experience %\", [Teachers_%Experience],",
              "        \"% Req Immunizations\", [Students_%Immune],",
              "        \"% Students Free/Reduced Lunch\", [Students_%FRPL],",
              "        \"Teacher Retention %\", [Teacher_%Retention],",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "isHidden": true,
            "lineageTag": "649e42dc-5da8-4b8e-b775-110ad95ba158"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "ea966269ad2547f5a673ecbd600aeccb"
          }
        ]
      },
      {
        "name": "@DynamicMeasureTable_Axis2",
        "description": "Disconnected table for allowing users to select their measure of choice for the y-axis of the scatter plot on the School Analysis page",
        "isHidden": true,
        "lineageTag": "b1006fcb-d41a-4231-9960-503049ff2ca5",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Axis 2 Measure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Measure name column of disconnected table",
            "isHidden": true,
            "sourceColumn": "[Axis 2 Measure]",
            "sortByColumn": "Sort Order",
            "lineageTag": "d30b047d-cbec-43a3-b5ee-dcf835714cb2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Sort Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "description": "Sort order of measure name column",
            "isHidden": true,
            "sourceColumn": "[Sort Order]",
            "formatString": "0",
            "lineageTag": "c1906830-d71c-408e-a5b7-076ea666ae99",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@DynamicMeasureTable_Axis2-ffe48997-8659-4605-9f13-b4cca2cce3bb",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "DATATABLE (",
                "    \"Axis 2 Measure\", STRING,",
                "    \"Sort Order\", INTEGER,",
                "    {",
                "        { \"% Students of Color\", 1 },",
                "        { \"% Teachers of Color\", 2 },",
                "        { \"Teacher Experience %\", 3 },",
                "        { \"% Req Immunizations\", 4 },",
                "        { \"% Students Free/Reduced Lunch\", 5 },",
                "        { \"Teacher Retention %\", 6 }",
                "    }",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Y-Axis",
            "description": "DAX measure for users' selected x-axis measure",
            "expression": [
              "VAR Selection =",
              "    SELECTEDVALUE ( '@DynamicMeasureTable_Axis2'[Axis 2 Measure] )",
              "RETURN",
              "    SWITCH (",
              "        Selection,",
              "        \"% Students of Color\", [Students_%POC],",
              "        \"% Teachers of Color\", [Teachers_%POC],",
              "        \"Teacher Experience %\", [Teachers_%Experience],",
              "        \"% Req Immunizations\", [Students_%Immune],",
              "        \"% Students Free/Reduced Lunch\", [Students_%FRPL],",
              "        \"Teacher Retention %\", [Teacher_%Retention],",
              "        BLANK ()",
              "    )"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "isHidden": true,
            "lineageTag": "1cbc65ad-62ee-435f-ba2b-b247171cfd83"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "3cd90b5cd4df490c8d4efa300d7a1a0f"
          }
        ]
      },
      {
        "name": "DIM_EventType",
        "description": "Event types",
        "lineageTag": "27b97e85-56dc-4ac4-a6c6-2af69705cc35",
        "columns": [
          {
            "name": "Event Type ID",
            "dataType": "int64",
            "description": "Primary key",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "Event Type ID",
            "formatString": "0",
            "isAvailableInMdx": false,
            "lineageTag": "5ea1a569-41c3-4a52-a62a-5212386b8f25",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Event Type",
            "dataType": "string",
            "description": "Event type description",
            "sourceColumn": "Event Type",
            "lineageTag": "cdd9b110-c102-44de-9772-d1c0ea20c25e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DIM_EventType",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    // Source",
                "    Source = Source_Events,",
                "",
                "    // Remove extraneous columns not needed in Power BI dashboard",
                "    SelEventTypeCol = Table.SelectColumns(Source, {\"Event Type\"}),",
                "    ",
                "    // Set column data types",
                "    SetDataTypes = Table.TransformColumnTypes(SelEventTypeCol,{{\"Event Type\", type text}}),",
                "    ",
                "    // Remove Duplicate Values",
                "    RemoveDuplicates = Table.Distinct(SetDataTypes),",
                "",
                "    // Create Primary key",
                "    PrimaryKey_Task1 = Table.AddIndexColumn(RemoveDuplicates, \"Index\", 1, 1, Int64.Type),",
                "    PrimaryKey_Task2 = Table.ReorderColumns(PrimaryKey_Task1,{\"Index\", \"Event Type\"}),",
                "    PrimaryKey_Task3 = Table.RenameColumns(PrimaryKey_Task2,{{\"Index\", \"Event Type ID\"}})",
                "",
                "in",
                "    PrimaryKey_Task3"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "@LastRefresh",
        "description": "M-calculated table storing last model refresh date/time, adjusted for Power BI service and DST.",
        "lineageTag": "c6d22ac7-7ff4-4fda-a128-1eccf1d7da92",
        "columns": [
          {
            "name": "DateTime",
            "dataType": "dateTime",
            "description": "last refresh date/time",
            "sourceColumn": "DateTime",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "6cdda2d2-1265-41f8-a9ca-64672bed9527",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "description": "last refresh date",
            "sourceColumn": "Date",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "ae5fb7bd-7b1d-4f4d-8e1b-3572069692fa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          },
          {
            "name": "Time",
            "dataType": "dateTime",
            "description": "last refresh time",
            "sourceColumn": "Time",
            "formatString": "Long Time",
            "lineageTag": "f4aa1db5-53e8-41d9-afbe-e32888d8591d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@LastRefresh",
            "mode": "import",
            "queryGroup": "Report Metadata",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "SummerTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 3, 14), Day.Sunday),",
                "WinterTimeStartDate = Date.StartOfWeek(#date(Date.Year(DateTime.LocalNow()), 10, 14), Day.Sunday),",
                "",
                "Timezonehours = if DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) < SummerTimeStartDate & #time(1, 0, 0) or",
                "DateTimeZone.RemoveZone(DateTimeZone.UtcNow()) > WinterTimeStartDate & #time(1, 0, 0) then",
                "-8 else -7,",
                "",
                "#\"Date and Time\" = DateTimeZone.SwitchZone(DateTimeZone.UtcNow(), Timezonehours, 0),",
                "",
                "#\"Converted to Table\" = #table(1, {{#\"Date and Time\"}}),",
                "",
                "#\"Renamed Columns\" = Table.RenameColumns(#\"Converted to Table\",{{\"Column1\", \"DateTime\"}}),",
                "",
                "#\"Changed Type\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"DateTime\", type datetimezone}}),",
                "",
                "#\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"DateTime\", \"DateTime - Copy\"),",
                "",
                "#\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column\",{{\"DateTime - Copy\", \"Date\"}}),",
                "",
                "#\"Duplicated Column1\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"Date\", \"Date - Copy\"),",
                "",
                "#\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column1\",{{\"Date - Copy\", type time}, {\"Date\", type date}}),",
                "",
                "#\"Renamed Columns2\" = Table.RenameColumns(#\"Changed Type1\",{{\"Date - Copy\", \"Time\"}})",
                "in",
                "",
                "#\"Renamed Columns2\""
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_ChangedProperties",
            "value": "[\"IsHidden\"]"
          }
        ]
      },
      {
        "name": "@KPISelection",
        "isHidden": true,
        "lineageTag": "c52c08f8-a70a-441f-ad50-b56a291ed1b6",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "KPI Selection",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "KPI Selection Order",
            "lineageTag": "fc259ddf-3cc8-4d5a-8041-13ef13ee29f5",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "KPI Selection Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "KPI Selection Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "KPI Selection Order",
            "lineageTag": "a6c3d9aa-e1f8-48ee-a474-03f38c2a2bcc",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "KPI Selection Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "59452b56-4bb2-44fd-bf73-f9b0c8e502fb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@KPISelection-94285d11-2e5f-4af8-a79c-7b61cbb97e26",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Events\", NAMEOF('@PeopleEventMeasures'[Events]), 0),",
                "    (\"Students Reached\", NAMEOF('@PeopleEventMeasures'[Students Reached]), 1),",
                "    (\"Duration (min)\", NAMEOF('@PeopleEventMeasures'[Duration]), 2)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e1d6a4d357fd43019f85376ffa773099"
          }
        ]
      },
      {
        "name": "@DimensionSelection",
        "isHidden": true,
        "lineageTag": "cdf7648f-3a93-4610-888d-c4d7571a3e7c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "DimensionSelection",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "DimensionSelection Order",
            "lineageTag": "dab1e6a3-fae9-4999-9ec0-5362fcc31767",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "DimensionSelection Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DimensionSelection Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "DimensionSelection Order",
            "lineageTag": "7a706b57-dae5-4a3e-b521-4b6f77fd4156",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "DimensionSelection Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "dff748f1-3db5-4840-83c5-b2ff803a4caa",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@DimensionSelection-2812c856-eb1f-4687-8fdc-b3f95b1218be",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"Educator\", NAMEOF('DIM_Educators'[Educator]), 0),",
                "    (\"Program Name\", NAMEOF('DIM_Programs'[Program Name]), 1),",
                "    (\"Grade\", NAMEOF('DIM_Grades'[Grade]), 2),",
                "    (\"Event Type\", NAMEOF('DIM_EventType'[Event Type]), 3)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a8d19eba65c349d69b71f95f3da13141"
          }
        ]
      },
      {
        "name": "@Geography",
        "isHidden": true,
        "lineageTag": "1637871f-281c-4062-b450-ea8b12d5ad98",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Geography",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Geography Order",
            "lineageTag": "70d7a059-1475-41b9-ac65-b4a06def6c50",
            "summarizeBy": "none",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Geography Fields"
                }
              ]
            },
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Geography Fields",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value2]",
            "sortByColumn": "Geography Order",
            "lineageTag": "b8ae9744-811a-4fbe-a5bb-0da37b57032f",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "ParameterMetadata",
                "value": {
                  "version": 3,
                  "kind": 2
                }
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Geography Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value3]",
            "formatString": "0",
            "lineageTag": "85e269ce-8190-440a-a37d-543440b40a92",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "@Geography-4f10049b-13c3-42dd-9abc-3f11664cb7d2",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "    (\"County\", NAMEOF('DIM_Schools'[County]), 0),",
                "    (\"District\", NAMEOF('DIM_Schools'[District Name]), 1)",
                "}"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "8855352f46564102a66ccb3f0ad4e1fb"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "3311c276-eed0-4114-88be-a0af88633bd6",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "Grade ID",
        "toTable": "DIM_Grades",
        "toColumn": "Grade ID"
      },
      {
        "name": "442d2aa5-b4d1-4003-a596-3ddc205e8dfa",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "Educator ID",
        "toTable": "DIM_Educators",
        "toColumn": "Educator ID"
      },
      {
        "name": "302e0c5b-86ea-4a5c-a5a7-890616531294",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "School ID",
        "toTable": "DIM_Schools",
        "toColumn": "School ID"
      },
      {
        "name": "b67357ef-834f-428c-848f-df9912ae9621",
        "fromTable": "FACT_SchoolData",
        "fromColumn": "School ID",
        "toTable": "DIM_Schools",
        "toColumn": "School ID"
      },
      {
        "name": "d24bae14-3dc6-40fe-a779-77fa13bd0725",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "Program ID",
        "toTable": "DIM_Programs",
        "toColumn": "Program ID"
      },
      {
        "name": "5844fcd6-871b-4440-ba5b-492f3d3a5bc5",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "Event Type ID",
        "toTable": "DIM_EventType",
        "toColumn": "Event Type ID"
      },
      {
        "name": "e26576cf-2e80-4cea-8d30-74747583c46a",
        "fromTable": "FACT_PeopleEvents",
        "fromColumn": "Event Date",
        "toTable": "DIMDate",
        "toColumn": "Date"
      }
    ],
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {}
      }
    ],
    "expressions": [
      {
        "name": "Source_Events",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect and extract Event sheet from Smartsheet API",
          "    Source = Smartsheet.Tables(),",
          "    #\"1469945008678788\" = Source{[Key=\"1469945008678788\"]}[Data],",
          "    #\"5824169314150276\" = #\"1469945008678788\"{[Key=\"5824169314150276\"]}[Data],",
          "    #\"3572369500465028\" = #\"5824169314150276\"{[Key=\"3572369500465028\"]}[Data],",
          "    #\"3663878065284996\" = #\"3572369500465028\"{[Key=\"3663878065284996\"]}[Data],",
          "     ",
          "    // Select Necessary Columns",
          "    ExtractNeededCols = Table.SelectColumns(#\"3663878065284996\",{\"Event Date\", \"Educator\", \"Event Type\", \"Program Name\", \"School Event Location\", \"Grade\", \"People\"}),",
          "    ",
          "    // Add Duration Column Based on Grade level (K - 5th = 45 minutes, all other grades = 60 minutes)",
          "    AddDurationCol = Table.AddColumn(ExtractNeededCols, \"Duration\", each if [Grade] = \"K\" then 45 else if [Grade] = \"1st\" then 45 else if [Grade] = \"2nd\" then 45 else if [Grade] = \"3rd\" then 45 else if [Grade] = \"4th\" then 45 else if [Grade] = \"5th\" then 45 else if [Grade] = \"Mixed Grades - Ele\" then 45 else 60),",
          "    ",
          "    // Set column data types",
          "    SetEventDate = Table.TransformColumnTypes(AddDurationCol, {{\"Event Date\", type date}}, \"en-US\"),",
          "    SetDataTypes = Table.TransformColumnTypes(SetEventDate,{{\"Educator\", type text}, {\"Event Type\", type text}, {\"Program Name\", type text}, {\"School Event Location\", type text}, {\"Grade\", type text}, {\"People\", Int64.Type}, {\"Duration\", Int64.Type}})",
          "in",
          "    SetDataTypes"
        ],
        "queryGroup": "Source Data",
        "lineageTag": "442b9f58-fbbd-4fa4-a6f2-41a3f5546ddc",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Source_Schools",
        "kind": "m",
        "expression": [
          "let",
          "    // Connect and extract Beta\\Sheets\\Schools sheet from Smartsheet API.  Note: This is 2020/21 year data, with 2019/20 year data only for closed schools; must update code when new data available",
          "    Source = Smartsheet.Tables(),",
          "    #\"1469945008678788\" = Source{[Key=\"1469945008678788\"]}[Data],",
          "    #\"5824169314150276\" = #\"1469945008678788\"{[Key=\"5824169314150276\"]}[Data],",
          "    #\"3572369500465028\" = #\"5824169314150276\"{[Key=\"3572369500465028\"]}[Data],",
          "    #\"8281918165804932\" = #\"3572369500465028\"{[Key=\"8281918165804932\"]}[Data],",
          "",
          "    // Remove school districts not served",
          "    RemoveUnservedDistricts = Table.SelectRows(#\"8281918165804932\", each ([District Name] <> \"Banks SD 13\" and [District Name] <> \"Canby SD 86\" and [District Name] <> \"Colton SD 53\" and [District Name] <> \"Corbett SD 39\" and [District Name] <> \"Estacada SD 108\" and [District Name] <> \"Gaston SD 511J\" and [District Name] <> \"Molalla River SD 35\" and [District Name] <> \"Scappoose SD 1J\" and [District Name] <> \"Scio SD 95\")),",
          "",
          "    // Select Necessary Columns",
          "    ExtractNeededCols = Table.SelectColumns(RemoveUnservedDistricts,{\"District Name\", \"School Name\", \"Street\", \"City\", \"State\", \"Zip\", \"County\", \"Lat\", \"Long\", \"Grades\", \"Total Students\", \"Student % Native\", \"Student % Asian\", \"Student % Black\", \"Student % Hispanic\", \"Student % Multi\", \"Student % Islander\", \"Student % White\", \"Total Teachers\", \"Teacher % Native\", \"Teacher % Asian\", \"Teacher % Black\", \"Teacher % Hispanic\", \"Teacher % Multi\", \"Teacher % Islander\", \"Teacher % White\", \"Required Immunizations\",\"Educational Assistants\", \"Teacher Experience\", \"Counselors/Psychologists\", \"Same Principal in the Last 3 Years\", \"Average Teacher Retention Rate\", \"Free/Reduced Price Lunch Eligible\", \"Title 1 School\" }),",
          "",
          "    // Set column data types",
          "    SetDataTypes = Table.TransformColumnTypes(ExtractNeededCols,{{\"District Name\", type text}, {\"School Name\", type text}, {\"Street\", type text}, {\"City\", type text}, {\"State\", type text}, {\"Zip\", Int64.Type}, {\"County\", type text}, {\"Grades\", type text}, {\"Total Students\", Int64.Type}, {\"Student % Native\", Percentage.Type}, {\"Student % Asian\", Percentage.Type}, {\"Student % Black\", Percentage.Type}, {\"Student % Hispanic\", Percentage.Type}, {\"Student % Multi\", Percentage.Type}, {\"Student % Islander\", Percentage.Type}, {\"Student % White\", Percentage.Type}, {\"Total Teachers\", Int64.Type}, {\"Teacher % Native\", Percentage.Type}, {\"Teacher % Asian\", Percentage.Type}, {\"Teacher % Black\", Percentage.Type}, {\"Teacher % Hispanic\", Percentage.Type}, {\"Teacher % Multi\", Percentage.Type}, {\"Teacher % Islander\", Percentage.Type}, {\"Teacher % White\", Percentage.Type}, {\"Required Immunizations\", Percentage.Type}, {\"Educational Assistants\", Int64.Type}, {\"Teacher Experience\", Percentage.Type}, {\"Counselors/Psychologists\", Int64.Type}, {\"Same Principal in the Last 3 Years\", type text}, {\"Average Teacher Retention Rate\", Percentage.Type}, {\"Free/Reduced Price Lunch Eligible\", Percentage.Type}, {\"Title 1 School\", type text}, {\"Lat\", type number}, {\"Long\", type number}})",
          "in",
          "    SetDataTypes"
        ],
        "queryGroup": "Source Data",
        "lineageTag": "4fb82b19-7d3a-4c2a-8045-d37f3a72bff9",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Source Data",
        "description": "Contains extract, untransformed raw data from data sources",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "DAX Containers",
        "description": "Computes specific, empty tables in the data model for containing DAX code",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Report Metadata",
        "description": "Contains queries that produce report metadata, like last refresh",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "PBIDesktopVersion",
        "value": "2.110.1085.0 (22.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"@SchoolMeasures\",\"Source_Events\",\"Source_Schools\",\"FACT_PeopleEvents\",\"FACT_SchoolData\",\"DIM_EventType\",\"DIM_Grades\",\"DIM_Schools\",\"DIM_Programs\",\"DIM_Educators\",\"@PeopleEventMeasures\",\"@FormatLabelMeasures\",\"@LastRefresh\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}